### ISSUE TITLE
Need to finish VMController.py

### ISSUE THREAD

**Issue by TimurNurlygayanov** [rkhozinov/deployment_system#4]
Now we have many "TO DO" in this file, looks like we should perform refactoring for this class and implement all necessary methods.

Also, please, fix comments for all methods.

**Comment by rkhozinov** [comment]
Yes. I wait for the serial port support in the Hatchery library. Now VM
controller works as module, that configure exist virtual machines (tested
only Vyatta machines).

On Tuesday, May 14, 2013, Timur Nurlygayanov wrote:

> Now we have many "TO DO" in this file, looks like we should perform
> refactoring for this class and implement all necessary methods.
> 
> Also, please, fix comments for all methods.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rkhozinov/deployment_system/issues/4
> .

## 

With best regards,
Hozinov Ruslan

Saratov, Russia, UTC+04:00
Mobile:               +7 937-638-45-89
E-mail:                fallrabble@gmail.com

**Comment by rkhozinov** [comment]
All functional moved to VirtualMachine class
